# Generated by Django 5.2.17 on 2026-08-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('COACH', 'Coach'), ('THINKING', 'Thinking partner')], default='COACH', max_length=10),
        ),
    ]
