# Generated by Django 5.2.17 on 2026-08-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tone',
        ),
    ]
