# Generated by Django 5.2.17 on 2026-08-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_checkin_phase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkin',
            name='one_checkin_per_goal_per_day',
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('pm_proof_text', '')), fields=('goal', 'date'), name='one_open_checkin_per_goal_per_day'),
        ),
    ]
