# Generated by Django 5.2.17 on 2026-08-05 17:38

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_message_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ABANDONED', 'Abandoned'), ('COMPLETED', 'Completed')], max_length=12)),
                ('reason', models.TextField()),
                ('phase_reached', models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch')], max_length=12)),
                ('contact_proofs', models.PositiveIntegerField(default=0)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('coach_reaction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement', to='coach.goal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
