# Generated by Django 5.2.17 on 2026-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_retirement_accepted_proofs'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='declaration_fit',
            field=models.CharField(choices=[('UNJUDGED', 'Not judged'), ('ON_PHASE', 'On phase'), ('OFF_PHASE', 'Off phase')], default='UNJUDGED', max_length=12),
        ),
        migrations.AddField(
            model_name='checkin',
            name='declaration_reaction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='proof_ask',
            field=models.TextField(blank=True),
        ),
    ]
