# Generated by Django 5.2.17 on 2026-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_checkin_declaration_fit_checkin_declaration_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='proof_image_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
