# Generated by Django 5.2.17 on 2026-08-07 19:51

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_proofattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_on', models.DateField()),
                ('kind', models.CharField(choices=[('NEW', 'New'), ('CHANGED', 'Changed'), ('FIXED', 'Fixed'), ('METHOD', 'Method')], default='CHANGED', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Unticked entries are kept but not shown to anyone.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'ordering': ['-shipped_on', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
