# Generated by Django 5.2.17 on 2026-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_changelog_thinking_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='proof_offer',
            field=models.TextField(blank=True),
        ),
    ]
