# Generated by Django 5.2.17 on 2026-08-09 20:12
#
# Message.Role gains SYSTEM — the app's own note about a turn the model
# dropped, which used to be stored as something Masterji said. Choices only:
# no column changes, and nothing to backfill, because every row written before
# this is genuinely USER or COACH.
#
# Renumbered twice — from 0040, then 0041 — onto
# 0041_changelog_answer_the_question_asked, the leaf at the time of the PR. Both
# collisions landed on main while this branch was open. Check the leaf again
# immediately before the merge button: two leaves stop main deploying, not just
# this branch.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0041_changelog_answer_the_question_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('COACH', 'Coach'), ('SYSTEM', 'System')], max_length=8),
        ),
    ]
