# Generated by Django 5.2.17 on 2026-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0044_changelog_whats_new_arrives_later'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='proof_status',
            field=models.CharField(choices=[('NONE', 'No proof yet'), ('ACCEPTED', 'Accepted'), ('PUSHED_BACK', 'Pushed back'), ('UNJUDGED', 'Not judged')], default='NONE', max_length=12),
        ),
    ]
