# Generated by Django 5.2.17 on 2026-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0055_changelog_people_and_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='phase',
            field=models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], max_length=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='phase',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], default='IDEA', max_length=12),
        ),
        migrations.AlterField(
            model_name='goalretirement',
            name='phase_reached',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='phase',
            field=models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], max_length=12),
        ),
        migrations.AlterField(
            model_name='phasetransition',
            name='from_phase',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], max_length=12),
        ),
        migrations.AlterField(
            model_name='phasetransition',
            name='to_phase',
            field=models.CharField(choices=[('IDEA', 'Idea'), ('VALIDATION', 'Validation'), ('BUILD', 'Build'), ('LAUNCH', 'Launch'), ('TRACTION', 'Traction')], max_length=12),
        ),
    ]
