# Generated by Django 5.2.17 on 2026-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0065_changelog_kind_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='url_alive',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='url_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofattempt',
            name='url_alive',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
