# Generated by Django 5.2.17 on 2026-08-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0071_the_first_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='brief',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
