# Generated by Django 5.2.17 on 2026-08-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0072_goal_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='last_digest_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('NOTICE', 'Notice'), ('DIGEST', 'Digest')], default='NOTICE', max_length=8),
        ),
    ]
