# Generated by Django 5.2.17 on 2026-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0073_goal_last_digest_week_message_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='considered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workshop',
            name='brief',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
