# Generated by Django 5.2.17 on 2026-08-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0074_the_workshop_survives_the_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sketch_parts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
