# Generated by Django 5.2.17 on 2026-08-14 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0075_the_bar_rehearsed_before_the_commit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='coach.goal'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REOPENED', 'Reopened'), ('SPENT', 'Spent')], default='OPEN', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('goal',), name='one_workshop_per_goal'),
        ),
    ]
