# Generated by Django 5.2.17 on 2026-08-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0076_the_room_reopens_once_per_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetransition',
            name='intent',
            field=models.TextField(blank=True),
        ),
    ]
