# Generated by Django 5.2.17 on 2026-08-14 01:31

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0076_what_this_phase_will_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('pond', models.CharField(choices=[('TALKED', 'The ones who talked to you'), ('ROOMS', 'The rooms they sit in'), ('PUBLIC', 'The public ponds'), ('ASK', 'The ask — charging or committed sign-ups')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_commitments', to='coach.goal')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
