# Generated by Django 5.2.17 on 2026-08-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0078_a_launch_date_the_server_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalretirement',
            name='share_slug',
            field=models.CharField(blank=True, default=None, max_length=22, null=True, unique=True),
        ),
    ]
