# Generated by Django 5.2.17 on 2026-08-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0079_the_record_as_a_page_you_can_hand_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='pivoted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='coach.goal'),
        ),
    ]
