# Generated by Django 5.2.17 on 2026-08-14 06:59
#
# Numbered 0082 over a leaf of 0080 on purpose: 0081 was spoken for by the
# session building #98 and had not been pushed when this was written. A gap in
# the numbering costs nothing — Django reads `dependencies`, not filenames —
# and it is cheaper than two branches arriving with the same name. The
# dependency below is the thing that has to be right, and it is re-checked
# against `check_migration_leaf` before push and again before merge.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0080_a_pivot_keeps_the_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='due_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
