# Generated by Django 5.2.17 on 2026-08-14 06:50
#
# Written as 0081 over a leaf of 0080, and renumbered to 0083 at merge time.
# 0081 was the number this session claimed on #98; #96's session read that claim
# and deliberately numbered itself 0082 over the same 0080 leaf rather than
# waiting, which is the right call — a gap costs nothing and two branches sharing
# a name costs a rebase. What it leaves behind is this: two migrations depending
# on one parent are two leaves, and `check_migration_leaf` is what said so. The
# rebase itself reported success, because git has no opinion about this graph.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0082_the_hour_they_named'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='metric_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='checkin',
            name='metric_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='metric_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
