# Generated by Django 5.2.17 on 2026-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0085_what_each_call_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcall',
            name='source',
            field=models.CharField(blank=True, choices=[('MESSAGE', 'Chat message'), ('WORKSHOP_MESSAGE', 'Workshop message'), ('CHECKIN', 'Check-in'), ('GOAL', 'Goal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelcall',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
