# Generated by Django 5.2.17 on 2026-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0086_which_turn_caused_the_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='sharpened',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='declaration_offer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='declaration_offer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
