# Generated by Django 5.2.17 on 2026-08-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0087_he_writes_the_morning_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='metric_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
