# Generated by Django 5.2.17 on 2026-08-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0088_he_heard_the_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetransition',
            name='intent_offer',
            field=models.TextField(blank=True),
        ),
    ]
