# Generated by Django 5.2.17 on 2026-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0089_he_heard_what_the_phase_is_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='launch_date_offer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='launch_pond_offer',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
