# Generated by Django 5.2.17 on 2026-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0090_he_heard_the_day_and_the_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title_offer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
